# Form implementation generated from reading ui file 'display.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1115, 824)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetNoConstraint)
        self.gridLayout.setContentsMargins(2, 2, 2, 2)
        self.gridLayout.setHorizontalSpacing(4)
        self.gridLayout.setVerticalSpacing(3)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.search_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.search_button.setMinimumSize(QtCore.QSize(40, 30))
        self.search_button.setObjectName("search_button")
        self.horizontalLayout_3.addWidget(self.search_button)
        self.connect_with_mac = QtWidgets.QPushButton(parent=self.centralwidget)
        self.connect_with_mac.setMinimumSize(QtCore.QSize(0, 30))
        self.connect_with_mac.setText("")
        self.connect_with_mac.setObjectName("connect_with_mac")
        self.horizontalLayout_3.addWidget(self.connect_with_mac)
        self.bground = QtWidgets.QPushButton(parent=self.centralwidget)
        self.bground.setEnabled(False)
        self.bground.setMinimumSize(QtCore.QSize(40, 30))
        self.bground.setText("")
        self.bground.setObjectName("bground")
        self.horizontalLayout_3.addWidget(self.bground)
        self.information_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.information_button.setMinimumSize(QtCore.QSize(40, 30))
        self.information_button.setText("")
        self.information_button.setObjectName("information_button")
        self.horizontalLayout_3.addWidget(self.information_button)
        self.minbutton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.minbutton.setMinimumSize(QtCore.QSize(40, 10))
        self.minbutton.setMaximumSize(QtCore.QSize(777777, 77777))
        self.minbutton.setText("")
        self.minbutton.setIconSize(QtCore.QSize(25, 30))
        self.minbutton.setObjectName("minbutton")
        self.horizontalLayout_3.addWidget(self.minbutton)
        self.maxbutton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.maxbutton.setMinimumSize(QtCore.QSize(40, 30))
        self.maxbutton.setText("")
        self.maxbutton.setIconSize(QtCore.QSize(45, 45))
        self.maxbutton.setObjectName("maxbutton")
        self.horizontalLayout_3.addWidget(self.maxbutton)
        self.quitbutton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.quitbutton.setMinimumSize(QtCore.QSize(40, 30))
        self.quitbutton.setText("")
        self.quitbutton.setIconSize(QtCore.QSize(30, 30))
        self.quitbutton.setObjectName("quitbutton")
        self.horizontalLayout_3.addWidget(self.quitbutton)
        self.horizontalLayout_3.setStretch(2, 25)
        self.horizontalLayout_3.setStretch(3, 2)
        self.horizontalLayout_3.setStretch(4, 2)
        self.horizontalLayout_3.setStretch(5, 2)
        self.horizontalLayout_3.setStretch(6, 2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.image_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.image_label.setText("")
        self.image_label.setObjectName("image_label")
        self.horizontalLayout.addWidget(self.image_label)
        self.image_layout = QtWidgets.QHBoxLayout()
        self.image_layout.setObjectName("image_layout")
        self.horizontalLayout.addLayout(self.image_layout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.instruction_text = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.instruction_text.setObjectName("instruction_text")
        self.verticalLayout.addWidget(self.instruction_text)
        self.verticalLayout.setStretch(0, 15)
        self.verticalLayout.setStretch(1, 5)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout.setStretch(1, 6)
        self.horizontalLayout.setStretch(2, 4)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.connect_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.connect_button.setMinimumSize(QtCore.QSize(0, 40))
        self.connect_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.connect_button.setObjectName("connect_button")
        self.horizontalLayout_2.addWidget(self.connect_button)
        self.cancel_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.cancel_button.setMinimumSize(QtCore.QSize(0, 40))
        self.cancel_button.setMaximumSize(QtCore.QSize(0, 16777215))
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout_2.addWidget(self.cancel_button)
        self.device_list = QtWidgets.QComboBox(parent=self.centralwidget)
        self.device_list.setEnabled(True)
        self.device_list.setMinimumSize(QtCore.QSize(0, 40))
        self.device_list.setCurrentText("")
        self.device_list.setObjectName("device_list")
        self.horizontalLayout_2.addWidget(self.device_list)
        self.accept_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.accept_button.setMinimumSize(QtCore.QSize(0, 40))
        self.accept_button.setObjectName("accept_button")
        self.horizontalLayout_2.addWidget(self.accept_button)
        self.deny_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.deny_button.setMinimumSize(QtCore.QSize(0, 40))
        self.deny_button.setObjectName("deny_button")
        self.horizontalLayout_2.addWidget(self.deny_button)
        self.horizontalLayout_2.setStretch(0, 4)
        self.horizontalLayout_2.setStretch(1, 4)
        self.horizontalLayout_2.setStretch(2, 2)
        self.horizontalLayout_2.setStretch(3, 2)
        self.horizontalLayout_2.setStretch(4, 2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.setStretch(1, 18)
        self.verticalLayout_2.setStretch(2, 1)
        self.gridLayout.addLayout(self.verticalLayout_2, 2, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.search_button.setText(_translate("MainWindow", "Tìm kiếm"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">Tên người vi phạm: Phạm Quốc Huy</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">Loại phương tiện: Ô tô</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">Biển kiểm soát: 18B-22212</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">Tốc độ vi phạm: 70km/h</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">Giới hạn tốc độ quy định: 50km/h</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">Thời điểm ghi nhận: 08/05/2024 R:35</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">Vị trí ghi nhận: </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">          Vĩ độ: 11° 29\' 24\'\' Bắc</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">          Kinh độ: 109° 27\' 36\'\' Đông</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">          Vị trí Km480-900</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">          QL1A-Hà Nội</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">Thiết bị: 01012 Kiểm định đến 10_2020</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">Đơn vị vận hành: Phòng Cảnh sát Giao thông Công an tỉnh Hà Nội</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:16pt;\"><br /></p></body></html>"))
        self.connect_button.setText(_translate("MainWindow", "Bật Bluetooth"))
        self.cancel_button.setText(_translate("MainWindow", "Đã kết nối Bluetooth! Nhấn để hủy"))
        self.accept_button.setText(_translate("MainWindow", "Đồng ý"))
        self.deny_button.setText(_translate("MainWindow", "Từ chối"))
